### ISSUE TITLE
Using JwtAuthenticate method at controller

### ISSUE THREAD

**Issue by danielfpedro** [ADmad/cakephp-jwt-auth#21]
It is possible?? I need use your `::getToken()`.

**Comment by ADmad** [comment]
The reason for making that method public was so that one could do `$this->Auth->authenticationProvider()->getToken()`.

But I see now that `AuthComponent` doesn't cache a reference to provider in case of stateless authentication. I'll submit a patch for `AuthComponent` for that.

In the meantime you should be able to use `$this->Auth->authenticationProvider()->getToken()` after calling `$this->Auth->identify()`.

**Comment by danielfpedro** [comment]
Thanks lord

**Comment by ADmad** [comment]
I have made PR cakephp/cakephp#7772 as per what I described above.

Once it's merged you can use Cake's master branch or wait for next release to be able to use `$this->Auth->authenticationProvider()->getToken()` without doing anything extra.
