### ISSUE TITLE
Authorization header different that bearer throws wrong exception.

### ISSUE THREAD

**Issue by ghost** [ADmad/cakephp-jwt-auth#43]
When adding a different header value than bearer combined with the token an  'UnexpectedValueException' with message 'Wrong number of segments'. This prevents other authentication handlers from using the authorization header for authentication.

**Comment by ADmad** [comment]
If you set `unauthenticatedException` config to `false` no exception will be thrown with debug off.

**Comment by Mesterjagel** [comment]
Hey ADmad, I'm sorry I mistakenly opened the issue from our company account. I guess it's still not wanted behaviour? I can upload a small fix if you want it:)

**Comment by hmic** [comment]
I've run into issue that too and just disabling the exception is not a solution, as I do have multiple Auth options available, one happens to be Basic, which sends - you guessed it - an "Authorized: Basic a76fed6548ce" header, that causes the exception instead of just calling the next Auth method in turn :p
