### ISSUE TITLE
Security paper

### ISSUE THREAD

**Issue by dereuromark** [ADmad/cakephp-jwt-auth#85]
https://research.securitum.com/jwt-json-web-token-security/

It might be worth for both the library owner as well as users to double check any of the more troubling security issues possible.
Probably also making sure any of the weak implementation details of this standard are not allowed etc.

EDIT:
Apparently https://paseto.io/ is the safer alternative.

They both however should not be used for stateless session management:

> Neither JWT nor Paseto were designed for stateless session management, which is "largely an anti-pattern". 

Not even Paseto can prevent replay attacks by itself.

**Comment by ADmad** [comment]
To the best of my knowledge I have used safe defaults.

By default the plugin only uses the `HS256` algo. Also it only does authentication, using the `sub` claim to fetch matching user from database. It doesn't do any authorization or maintain state so replay attacks are a non issue. Proper composer constraints are used so that latest version of `firebase/php-jwt` is used.

So I guess I can link to the article you have referenced in the plugin readme and leave it to users to decided if using JWT is the right option for their use case.

**Comment by dereuromark** [comment]
Was the link and info about stateless session management attack vectors added to readme? For users to know the issues at hand?
