### ISSUE TITLE
Add new variable in json

### ISSUE THREAD

**Issue by Maniraj-Webner** [ADmad/cakephp-jwt-auth#93]
@ADmad 

I'm looking to add a variable in the below response. like "is_token_valid" : "true". How can I do this ? could you tell me?
{
    "message": "Signature verification failed",
    "url": "/api/is_token_valid",
    "code": 401
}

or

{
    "message": "Expired token",
    "url": "/api/is_token_valid",
    "code": 401
}

**Desired Json**
{
    "message": "Expired token",
    "url": "/api/is_token_valid",
    "code": 401,
    "is_token_valid" : true

}

I'm doing this because I need to check that the token is valid or not

**Comment by ADmad** [comment]
Use a [custom error controller](https://book.cakephp.org/4/en/development/errors.html#custom-errorcontroller) or [custom exception renderer](https://book.cakephp.org/4/en/development/errors.html#custom-exceptionrenderer) to modify the response as needed.

If required you can use the `unauthenticatedException` config to make the authenticator throw the exception you need instead of default `UnauthorizedException`.
